language: node_js
node_js:
  - '6.10.0'
after_script: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < lcov.info